#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

random_key=$(ynh_string_random --length=32)
email=$(ynh_user_get_info --username=$admin --key="mail")

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --key=random_key --value=$random_key

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Configuring PHP-FPM..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# INSTALL COMPOSER DEPENDENCIES
#=================================================
ynh_script_progression "Installing composer dependencies..."

ynh_composer_install
ynh_composer_exec install --no-dev

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 600 $install_dir/.env

#==================================================
# FIX PHP VERSION
#==================================================
ynh_script_progression "Fixing php version in package.json..."

ynh_replace --file="$install_dir/package.json" --match="php artisan lang:generate -vvv" --replace="php$php_version artisan lang:generate -vvv"

#=================================================
# DEPLOY
#=================================================
ynh_script_progression "Deploying..."

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app yarn install
	ynh_hide_warnings ynh_exec_as_app yarn run production
	ynh_hide_warnings ynh_exec_as_app php$php_version artisan setup:production --force --email=$email --password=$password
	ynh_hide_warnings ynh_exec_as_app php$php_version artisan passport:client --password -n > key.txt
	mobile_id=$( cd $install_dir && tail -2 key.txt | head -1 | cut -c 12- )
	mobile_key=$( cd $install_dir && tail -1 key.txt | cut -c 16- )
	ynh_replace  --match="mobile_id"  --replace="$mobile_id"  --file="$install_dir/.env"
	ynh_replace  --match="mobile_key" --replace="$mobile_key" --file="$install_dir/.env"
	ynh_app_setting_set --key=mobile_id --value=$mobile_id
	ynh_app_setting_set --key=mobile_key --value=$mobile_key
	ynh_safe_rm "$install_dir/key.txt"
	ynh_hide_warnings ynh_exec_as_app php$php_version artisan config:cache
    ynh_hide_warnings ynh_exec_as_app php$php_version artisan optimize:clear
popd

ynh_store_file_checksum "$install_dir/.env"

#=================================================
# INSTALL THE CRON FILE
#=================================================
ynh_script_progression "Setuping a cron..."

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
