#!/bin/bash

set -u

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers
source ./_common.sh

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)

# Remove sources
sudo rm -rf /var/www/$app

# Remove nginx configuration file
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Remove cronjob
sudo rm -f /etc/cron.d/$app

# Remove PHP7.0
ynh_remove_php7

# Remove mysql user and database
dbname=$app
dbuser=$app
ynh_mysql_drop_db "$dbname" || true
ynh_mysql_drop_user "$dbuser" || true

# Reload nginx service
sudo service nginx reload
