#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the dedicated PHP-FPM config
ynh_config_remove_phpfpm

# Remove metapackage and its dependencies
ynh_nodejs_remove

# Remove a cron file
ynh_safe_rm "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
