#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path)
admin=$(ynh_app_setting_get $app admin)
is_public=$(ynh_app_setting_get $app is_public)
final_path=$(ynh_app_setting_get $app final_path)
db_name=$(ynh_app_setting_get $app db_name)
db_pwd=$(ynh_app_setting_get $app mysqlpwd)
language=$(ynh_app_setting_get $app language)
random_key=$(ynh_app_setting_get $app random_key)
#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

if [ "$is_public" = "Yes" ]; then
	ynh_app_setting_set $app is_public 1	# Fix is_public as a boolean value
	is_public=1
elif [ "$is_public" = "No" ]; then
	ynh_app_setting_set $app is_public 0
	is_public=0
fi

if [ -z $db_name ]; then	# If db_name doesn't exist, create it
	db_name=$(ynh_sanitize_dbid $app)
	ynh_app_setting_set $app db_name $db_name
fi
#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# CHECK THE PATH
#=================================================

# Normalize the URL path syntax
path_url=$(ynh_normalize_url_path $path_url)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source "$final_path"

#=================================================
# INSTALL COMPOSER
#=================================================
init_composer $final_path

#=================================================
# NGINX CONFIGURATION
#=================================================

# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# CREATE DEDICATED USER
#=================================================

# Create a system user
ynh_system_user_create $app


#=================================================
# SPECIFIC UPGRADE
#=================================================

# install new dependencies
ynh_install_app_dependencies php7.1 php7.1-cli php7.1-common php7.1-json php7.1-opcache php7.1-mysql php7.1-mbstring php7.1-mcrypt php7.1-zip php7.1-fpm php7.1-bcmath php7.1-intl php7.1-simplexml php7.1-dom php7.1-curl php7.1-gd

#=================================================
# PHP-FPM 7.1 CONFIGURATION
#=================================================

# Create a dedicated php-fpm7.1 config
ynh_add_fpm7.1_config

# setup application config
# Get admin email
email=$(ynh_user_get_info $admin 'mail')
sudo  cp ../conf/.env $final_path/.env

db_name=$(ynh_sanitize_dbid $app)

ynh_replace_string  "random_key" "$random_key" "$final_path/.env"
ynh_replace_string  "yunouser"   "$db_name"    "$final_path/.env"
ynh_replace_string  "yunopass"   "$db_pwd"     "$final_path/.env"
ynh_replace_string  "yunobase"   "$db_name"    "$final_path/.env"
ynh_replace_string  "yunomail"   "$email"      "$final_path/.env"
ynh_replace_string  "yunodomain" "$domain"     "$final_path/.env"
ynh_replace_string  "language"   "$language"   "$final_path/.env"


# Run monica update
cd $final_path && sudo /usr/bin/php7.1 artisan monica:update --force

if [ -f $final_path/storage/oauth-private.key ]; then
	mobile_id=$(ynh_app_setting_get $app mobile_id)
	mobile_key=$(ynh_app_setting_get $app mobile_key)
else
	( cd $final_path && sudo /usr/bin/php7.1 artisan passport:client --password -n > key.txt )
	mobile_id=$( cd $final_path && tail -2 test.txt | head -1 | cut -c 12- )
	mobile_keykey=$( cd $final_path && tail -1 key.txt | cut -c 16- )
	ynh_replace_string  "__IDENTITY__"   "$id"   "$final_path/.env"
	ynh_replace_string  "__KEY__"        "$key"  "$final_path/.env"
	ynh_app_setting_set $app mobile_id $mobile_id
	ynh_app_setting_set $app mobile_key $mobile_key
	(cd $final_path && rm -f key.txt)
	(cd $final_path && sudo /usr/bin/php7.1 artisan monica:update --force)
fi
#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set right permissions for curl installation
chown -R $app: $final_path

#=================================================
# SETUP SSOWAT
#=================================================

if [ $is_public -eq 0 ]
then	# Remove the public access
	ynh_app_setting_delete $app skipped_uris
fi
# Make app public if necessary
if [ $is_public -eq 1 ]
then
	# unprotected_uris allows SSO credentials to be passed anyway
	ynh_app_setting_set $app unprotected_uris "/"
fi

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx
# Set default php to php5 or php7.0
if [ "$(lsb_release --codename --short)" == "jessie" ]; then
	update-alternatives --set php /usr/bin/php5
else
    update-alternatives --set php /usr/bin/php7.0
fi
